### ISSUE TITLE
Install flag

### ISSUE THREAD

**Issue by sushain97** [unhammer/apertium-get#3]
My current usage looks like this:

```dockerfile
RUN apertium-get en-es
RUN cd apertium-en-es && make install && ln -s /usr/local/share/apertium/apertium-en-es /usr/share/apertium/apertium-en-es

RUN apertium-get nno-nob
RUN cd apertium-nno && make install && ln -s /usr/local/share/apertium/apertium-nno /usr/share/apertium/apertium-nno
RUN cd apertium-nob && make install && ln -s /usr/local/share/apertium/apertium-nob /usr/share/apertium/apertium-nob
RUN cd apertium-nno-nob && make install && ln -s /usr/local/share/apertium/apertium-nno-nob /usr/share/apertium/apertium-nno-nob
```

A flag to `apertium-get` that also runs `make install` (for dependencies as well?) would be appreciated.

**Comment by unhammer** [comment]
why not use the .deb's then?

**Comment by sushain97** [comment]
Hm I wasn't sure whether they came with the tagger, analysis, etc. modes.

**Comment by unhammer** [comment]
I think the packages include pretty much what is installed by `make install`.

```
$ dpkg -L apertium-nno|grep modes
/usr/share/apertium/modes
/usr/share/apertium/modes/nno-disam.mode
/usr/share/apertium/modes/nno-gener.mode
/usr/share/apertium/modes/nno-morph.mode
/usr/share/apertium/modes/nno-syntax.mode
/usr/share/apertium/modes/nno-tagger.mode
```

(If a package doesn't install a mode that should be installed, you can edit modes.xml to say `install="yes"` on that mode, and edit Makefile.am to ensure there's a line somewhere saying `install-data-local: install-modes`)

-----

`apertium-get` was mostly intended to make it easy for new language pair hackers to get their source folders set up quickly. And they tend to do `sudo` too much, which leaves them with root-owned files in places where they shouldn't be and more support work in `#apertium`. I'd prefer to have this command be fairly goofproof, but if the docs say "you may have to use `sudo` if you want to install" then people will think "oh I probably should install" and they'll start sudoing all over their stuff. 

OTOH, installing to a `--prefix` should be fairly safe (and I see you're essentially using a different prefix anyway because of your symlinks).

**Comment by sushain97** [comment]
> I'd prefer to have this command be fairly goofproof, but if the docs say "you may have to use sudo if you want to install" then people will think "oh I probably should install" and they'll start sudoing all over their stuff.

Haha!

> I think the packages include pretty much what is installed by make install.

Well, this is for APy so I pass the source directory to `--non-pairs-path` (https://github.com/goavki/apertium-html-tools/blob/master/docker/apy.Dockerfile#L53-L71). I think we did this because lots of packages aren't set up properly. Ergo, I need the source and `apertium-get` is the simplest solution? Perhaps I don't actually need `make install` and only need the symlinks? I added the symlinks since `apertium-tagger` and friends were looking for things there and couldn't find them.

> And they tend to do sudo too much, which leaves them with root-owned files in places where they shouldn't be and more support work in #apertium.

FWIW, all the commands here are run as `sudo` :) (I hope Apertium/APy doesn't have any arbitrary code execution bugs)

**Comment by unhammer** [comment]
If packages install the modes that you want, then `--non-pairs-path` shouldn't be needed. If they don't install the modes you want, then `make install` doesn't help anyway …
That option was there because we at some point wanted to *skip* the pair-modes when pointing APy directly at the (non-installed!) source directories. E.g. `servlet.py /usr/share/apertium --non-pairs-path ~/src/apertium-svn` would take everything it found in `/usr/share/apertium/modes` but skip the pairs when getting modes from `~/src/apertium-svn`. I guess the reason for skipping was having only releases run as translator pairs, while letting anything go as analysers.

**Comment by sushain97** [comment]
> I guess the reason for skipping was having only releases run as translator pairs, while letting anything go as analysers.

Yep, that sounds like it was the intent. Unless I'm missing something, that means I need the source and can't use the packages.

It appears that this works and is the simplest solution:

```dockerfile
# Install Apertium data

WORKDIR /source

ADD https://raw.githubusercontent.com/unhammer/apertium-get/master/apertium-get .
RUN chmod +x apertium-get

RUN apertium-get en-es
RUN apertium-get kaz-tat
RUN apertium-get nno-nob

EXPOSE 2737
CMD ["python3", \
    "/root/apertium-apy/servlet.py", "/source", \
    "--lang-names", "/root/apertium-apy/langNames.db" \
]
```

```
apy_1         | [I 170619 08:42:06 servlet:1133] 15 pair modes found
apy_1         | [I 170619 08:42:06 servlet:1133] 13 analyzer modes found
apy_1         | [I 170619 08:42:06 servlet:1133] 7 generator modes found
apy_1         | [I 170619 08:42:06 servlet:1133] 13 tagger modes found
```

It appears I had made the classic mistake of royally overcomplicating everything.
